// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8yBD2_-5blvdnDmPe3CS_Jo_CK4dcgSk',
    appId: '1:841540555936:web:21b5ea4d212829e5f125c5',
    messagingSenderId: '841540555936',
    projectId: 'age-estim',
    authDomain: 'age-estim.firebaseapp.com',
    databaseURL: 'https://age-estim-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'age-estim.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAimjJUsd0UbSjOppBSeMcqhR9KPO3K6MY',
    appId: '1:841540555936:android:1bc370130f3d5ea1f125c5',
    messagingSenderId: '841540555936',
    projectId: 'age-estim',
    databaseURL: 'https://age-estim-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'age-estim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsRuqEv0gVopx7Fx4T6_He_KCsf2XKjok',
    appId: '1:841540555936:ios:31cea4c7c5005093f125c5',
    messagingSenderId: '841540555936',
    projectId: 'age-estim',
    databaseURL: 'https://age-estim-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'age-estim.appspot.com',
    iosBundleId: 'com.example.ageRecogPkl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsRuqEv0gVopx7Fx4T6_He_KCsf2XKjok',
    appId: '1:841540555936:ios:14860c7d585fbab3f125c5',
    messagingSenderId: '841540555936',
    projectId: 'age-estim',
    databaseURL: 'https://age-estim-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'age-estim.appspot.com',
    iosBundleId: 'com.example.ageRecogPkl.RunnerTests',
  );
}
